Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.135.15"
  config.vm.network "forwarded_port", guest: 22, host: "2200", id: "ssh"
  config.vm.provision :shell, inline: '(sudo yum  -y  update)'
end
