Vagrant.configure(2) do |config|
  config.vm.define "control", primary: true do |config1|
    config1.vm.box = "ubuntu/focal64"
    config1.vm.hostname =  "control"
    config1.vm.network "private_network", ip: "192.168.135.140"
    config1.vm.network "forwarded_port", guest: 22, host: "2200", id: "ssh"
    config1.vm.provision :shell, inline: "echo 'export ANSIBLE_CONFIG=/vagrant/ansible/ansible.cfg' >> /home/vagrant/.bash_profile"
    config1.vm.provision :shell, inline: 'sudo apt-get update; sudo yum install python-requests; sudo apt-get autoremove -y; sudo apt-add-repository -y ppa:ansible/ansible; sudo apt-get install -y ansible=2.9.6+dfsg-1 software-properties$
    config1.vm.provision :shell, :inline => <<'EOF'
        if [ ! -f "/home/vagrant/.ssh/id_rsa" ]; then
  ssh-keygen -t rsa -N "" -f /home/vagrant/.ssh/id_rsa
fi
cp /home/vagrant/.ssh/id_rsa.pub /vagrant/control.pub
cat << 'SSHEOF' > /home/vagrant/.ssh/config
Host *
  StrictHostKeyChecking no
  UserKnownHostsFile=/dev/null
SSHEOF
chown -R vagrant:vagrant /home/vagrant/.ssh/
EOF
  end

  config.vm.define "wordpress" do |config2|
    config2.vm.box = "ubuntu/focal64"
    config2.vm.hostname = "wordpress"
    config2.vm.network "private_network", ip: "192.168.135.141"
    config2.vm.network "forwarded_port", guest: 22, host: "2201", id: "ssh"
    config2.vm.provision :shell, inline: 'cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys'
    config2.vm.provision :shell, inline: 'test -e /usr/bin/python || (apt -y update && apt install -y python)'
  end

end
