---
system_user: vagrant
compose_project_dir: /home/{{ system_user }}/compose-wordpress
root_db_psw: 123
wp_version: 5.0.2
wp_db_name: wordpress
wp_db_host: mysql
wp_db_psw: wordpress
wp_db_user: wordpress
root_db_psw: 123
